### PR TITLE
use Asciidoctor reveal.js with online reveal.js

### PR DESCRIPTION
**Pull request by Bruno-366**
this way one doesn't need to add a local reveal.js file to the github repo

### CODE REVIEW

**Comment by manoelcampos** [comment]
Thanks for your contribution. It's really welcome.
But what about using the latest [4.1.0 release](https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/)?

**Comment by Bruno-366** [comment]
hmm, i suppose that could work, although I was suspecting that it might not be supported by `Asciidoctor reveal.js`

https://docs.asciidoctor.org/reveal.js-converter/latest/setup/compatibility-matrix/

What do you think?

**Comment by manoelcampos** [comment]
Well, in this case, let's go with the safe option.
Thanks for contributing.

**Review by manoelcampos — APPROVED** [review]

**Comment by manoelcampos** [comment]
Could you please try it? I don't have any reveal.js slides to build. You don't need to change the action version if you are using the v2 release.

**Comment by Bruno-366** [comment]
Yes I've tried it and it works using the online file fetched from cdnjs.cloudflare

**Pull request merged**
